'use strict';
let width = 5;
let height = 6;
let area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
let bill = 100.63;
let payment = 115;
let change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
let quizzes = 30;
let midterm = 120;
let final = 99;
let grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
let firstName = 'Andrew';
let lastName = 'Owyang';
let fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
let pH = 3;
let isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
let headCount = 14;
let isSparta = headCount == 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto = motto + ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
